name: scratch
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bitarray #=2.3.6
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - cryptography
  - cvxopt
  - dataclasses
  - dsdp
  - ffmpeg
  - fftw
  - filelock
  - freetype
  - giflib
  - glpk
  - gmp
  - gnutls
  - gsl
  - huggingface_hub
  - idna
  - importlib-metadata
  - importlib_metadata
  - joblib
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libffi
  - libidn2
  - liblapack
  - libopus
  - libpng
  - libtasn1
  - libtiff
  - libunistring
  - libuv
  - libvpx #
  - libwebp
  - libwebp-base
  - lz4-c
  - metis
  - mpfr
  - ncurses
  - nettle
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - pycparser
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pyyaml
  - readline
  - regex
  - requests
  - sacremoses
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - suitesparse
  - tbb
  - threadpoolctl
  - tk
  - tokenizers
  - torchaudio #
  - torchvision
  - tqdm
  - transformers
  - typing-extensions
  - typing_extensions
  - urllib3
  - wheel
  - x264 #
  - xz
  - yaml
  - zipp
  - zlib
  - zstd
